### ISSUE TITLE
redirect_to :back is deprecated in rails 5 and should not be used + error when no HTTP referrer. 

### ISSUE THREAD

**Issue by Erowlin** [userimpersonate/user_impersonate2#20]
In Rails5, `redirect_to :back` has been deprecated, now the proper way to redirect back is to use 
`redirect_back(fallback_location: root_path)`. Fallback location is used when no HTTP referrer is present. 

I think the logic in `controllers/user_impersonate/impersonate_controller.rb#current_user_must_be_staff!`  should be updated to use that new syntax whenever possible. `ActionController::RedirectBackError` does not exist anymore in Rails5, so this method would fail when there are no HTTP Referrer. 

I first started to update the `redirect_to :back` to the new syntax, but the Gem has to be compatible with Rails4 applications, so I'm not really sure what's the strategy to adopt in a gem. Should I detect the Rails version, and depending on the Rails version have two method definitions? 

Thanks :)

**Comment by rcook** [comment]
@Erowlin : Detecting the Rails version and selecting between two method definitions would be a reasonable approach.
